### ISSUE TITLE
The /#/ is not needed in the URL when posting to Slack. Because when you click on the link you go to the homepage

### ISSUE THREAD

**Issue by redmerloen** [wearespindle/flindt#43]
https://github.com/wearespindle/flindt/blob/60024d4dd349511db48099ea8f0cae5f99db4e0d/backend/flindt/feedback/models.py#L151

**Comment by ferdynice** [comment]
This is actually only the case for our own deployment, because the frontend files are not deployed yet. Thus using the old urls instead of hash urls.
